site_name: Documentación del Proyecto
nav:
  - Inicio: index.md
  - Manual de Usuario(md): Manual_de_Usuario.md
  - Guía de Referencia(md): Guia_de_Referencia.md
  - Guía de Instalación(md): Guia_de_Instalacion.md

  - Manual de Usuario(pdf): Manual_de_Usuario.pdf
  - Guía de Referencia(pdf): Guia_de_Referencia.pdf
  - Guía de Instalación(pdf): Guia_de_Instalacion.pdf
theme:
  name: "material"
